import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar, Footer } from "../Components";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}  {/* ✅ This ensures the page content is displayed */}
        <Footer />
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { NavBar,Footer } from '../Components';
// import './page'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ Component, pageProps }) {
//   return (
//     <html lang="en">
//       <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      // >
        // {/* {children} */}
        // <>
    // <NavBar/>
    // {/* <Component {...pageProps}/> */}
//     <Footer/>
//     </>
//       </body>
//     </html>
    
//   );
// }